### ISSUE TITLE
Potential issue on SAC implementation

### ISSUE THREAD

**Issue by ethanluoyc** [ku2482/rljax#10]
Hi!

Thanks for the implementation for a really exhaustive list of RL algorithms. I have been referring to this repo when trying to implement some of the RL algorithms in JAX.

I noticed that there might be an issue with the loss function for the temperature parameter in SAC and SAC-AE, but this may be present in potentially other variants of SAC. 

https://github.com/ku2482/rljax/blob/master/rljax/algorithm/sac.py#L267

I think it should be alpha instead log_alpha in the beginning, I cross-referenced with the `soft_learning` and this seems to be what they did. https://github.com/rail-berkeley/softlearning/blob/master/softlearning/algorithms/sac.py#L256

Also there may be some typos in SAC_AE. https://github.com/ku2482/rljax/blob/master/rljax/algorithm/sac_ae.py#L213, this is not the update_interval_ae in the constructor.

Best,
YL

**Comment by toshikwa** [comment]
Hi, @ethanluoyc !

> I think it should be alpha instead log_alpha in the beginning, I cross-referenced with the soft_learning and this seems to be what they did.

That's true. However, using log_alpha instead of alpha is more common (maybe due to its stabilities), and I followed the [rllib](https://github.com/ray-project/ray/blob/master/rllib/agents/sac/sac_torch_policy.py#L292) which I think the most trustworty.
(Actually, I tested using alpha instead of log_alpha before, and the results were almost the same.)

> Also there may be some typos in SAC_AE

Sorry about that. I'll fix it later (though I don't have time now)

Thanks ;)

**Comment by ethanluoyc** [comment]
Yeah, regarding the log_alpha I also did an ablation on this by running SAC on dm_control suite, and I didn't notice any difference in the result, but I suspect the different formulation requires a different default for the target entropy though, but I don't have any insight on this.

BTW, have you seen https://github.com/deepmind/acme? I am mostly writing my agent based on the acme interface, it would be really great if rljax can provide some interop with acme.

**Comment by ethanluoyc** [comment]
BTW, would you be able to comment on the results you have for your SAC-AE implementation? I ported the code and is running some baseline benchmark to see whether anything breaks, it would be really useful if you can share some benchmark results that you have for SAC-AE on the dm_control suite.

**Comment by toshikwa** [comment]
> BTW, have you seen https://github.com/deepmind/acme? I am mostly writing my agent based on the acme interface

I'm aware of, but haven't read it yet.
There are too many RL libraries...

> it would be really great if rljax can provide some interop with acme.

I don't have time now, but I will definitely consider that (or you would like to implement?)

> would you be able to comment on the results you have for your SAC-AE implementation?

Did you check the benchmark results [here](https://github.com/ku2482/rljax#example)?

**Comment by ethanluoyc** [comment]
> but I will definitely consider that (or you would like to implement?)

Let me take a look at how to support that. One caveat is the acme uses a replay storage system called reverb which can be a heavy dependency, but I think for the time being your code is really good to showcase how to do similar things in acme!

> Did you check the benchmark results here?

Yeah I am aware of the original paper, but I have not matched the architectures exactly so..

**Comment by toshikwa** [comment]
> Yeah I am aware of the original paper, but I have not matched the architectures exactly so..

I shared my results here(https://github.com/ku2482/rljax#example), isn't it what you want?

![Screen Shot 2021-04-28 at 3 28 14](https://user-images.githubusercontent.com/37267851/116293464-e2341680-a7d1-11eb-921f-3cd04cf19f01.png)

**Comment by ethanluoyc** [comment]
Ah ok. I totally missed this section. The text is hidden at first glance..
